services:
  - type: web
    name: antilink-telegram-bot
    env: python
    region: singapore
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        value: 8058056389:AAEhCW2ZDxaV-3OqJDG3nIyTqsFzrZiWhyk
      - key: PYTHON_VERSION
        value: 3.12.0
